version: '3.7'

services:
  postgres:
    image: postgres:16.4-alpine3.20
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=api-velock
      - POSTGRES_PASSWORD=api-velock-pass
      - POSTGRES_DB=db-v1
    volumes:
      - api-velock-pg-db:/postgres

volumes:
  api-velock-pg-db: